#!/usr/bin/env python3
# Certificate manager using ACME protocol
#
# To install on Debian:
# apt-get install build-essential libssl-dev libffi-dev python3-dev python3-pip
# pip3 install -r requirements.txt
import os
import traceback

from certlib import AcmeError
from certlib.manager import AcmeManager

if __name__ == '__main__':  # called from the command line
    try:
        script_dir = os.path.dirname(os.path.realpath(__file__))
        ok, errors = AcmeManager(script_dir).run()
        if errors:
            exit(1)
    except AcmeError as e:
        traceback.print_exc()
        exit(1)
